name: Build and Release APK

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install EAS CLI and Dependencies
        run: |
          npm install -g eas-cli
          npm ci

      - name: Build APK (Local)
        # On utilise le token directement ici pour l'auth
        run: npx eas-cli build --platform android --local --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Rename and Prepare APK
        id: prep
        run: |
          VERSION=$(node -p "require('./package.json').version")
          APK_PATH=$(find . -name "*.apk" | head -n 1)
          FILENAME="octaramaps-${VERSION}.apk"
          mv "$APK_PATH" "$FILENAME"
          echo "filename=$FILENAME" >> $GITHUB_OUTPUT

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.prep.outputs.filename }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
